account/urls.py
from . import views
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView

app_name = 'account'
urlpatterns = [
    url(r'^password-change/$', PasswordChangeView.as_view(template_name='registration/password_change_form.html'),
        name='password_change'),
    url(r'^password-change/done/$', PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'),
        name='password_change_done'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', LoginView.as_view(template_name='registration/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='registration/logged_out.html'), name='logout'),
    # url(r'^logout-then-login/$', 'django.contrib.auth.views.logout_then_login', name='logout_then_login'),
    url(r'^my_page/$', views.self_page, name='account'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^add_animal/$', views.register_animal, name='add_animal'),
    url(r'^edit_animal/$', views.animal_edit, name='edit_animal'),
    url(r'^add_shelter/$', views.register_shelter, name='add_shelter'),
    url(r'^edit_shelter/$', views.edit_shelter, name='edit_shelter'),
    url(r'^page/$', views.page, name='page'),
]

animal_home/urls.py
from django.urls import path, include
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shelter/', include('shelter.urls')),
    path('account/', include('account.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shelter/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'shelter'
urlpatterns = [
    path('main/', views.index, name='index'),
    path('search_pet/', views.search_page, name='search_page'),
    path('search_pet/filter', views.search_filter, name='search_filter'),
]

shelter/models.py
from django.db import models
from django.conf import settings

class Color(models.Model):
    color_value = models.CharField(unique=True, max_length=50, null=True)

    def __str__(self):
        return self.color_value


class Weight(models.Model):
    weight_value = models.CharField(unique=True, max_length=50, null=True)

    def __str__(self):
        return self.weight_value


class Animal(models.Model):
    SEX_ANIMAL = (
        ('M', 'Кабель'),
        ('Ж', 'Сучка'),
    )
    KIND_ANIMAL = (
        ('С', 'Собака'),
        ('К', 'Кошка'),
    )
    WOOL_ANIMAL = (
        ('К', 'Короткая'),
        ('О', 'Обычная'),
        ('Д', 'Длинная'),
    )
    EARS_ANIMAL = (
        ('С', 'Стоячие'),
        ('П', 'Полустоячие'),
        ('В', 'Висячие'),
        ('К', 'Купированные'),
    )
    TAIl_ANIMAL = (
        ('С', 'Стоячие'),
        ('П', 'Полустоячие'),
        ('В', 'Висячие'),
        ('К', 'Купированные'),
    )
    animal_card = models.CharField(max_length=10, null=True, verbose_name="Номер карточки")
    animal_name = models.CharField(max_length=10, null=True, verbose_name="Кличка")
    animal_kind = models.CharField(max_length=10, choices=KIND_ANIMAL, null=True, verbose_name="Тип")
    animal_gender = models.CharField(max_length=10, choices=SEX_ANIMAL, verbose_name="Пол", null=True)
    animal_color = models.ForeignKey(Color, on_delete=models.CASCADE, max_length=20, null=True, verbose_name="Цвет")
    animal_ears = models.CharField(max_length=20, choices=EARS_ANIMAL, null=True, verbose_name="Уши")
    animal_tail = models.CharField(max_length=20, choices=TAIl_ANIMAL, null=True, verbose_name="Хвост")
    animal_age = models.CharField(max_length=20, null=True, verbose_name="Возраст")
    animal_breed = models.CharField(max_length=50, default='Метис', null=True, verbose_name="Порода")
    animal_size = models.CharField(max_length=10, null=True, verbose_name="Размер")
    animal_weight = models.ForeignKey(Weight, on_delete=models.CASCADE, max_length=20, null=True, verbose_name="Вес")
    animal_wool = models.CharField(max_length=10, choices=WOOL_ANIMAL, null=True, verbose_name="Шерсть")
    area = models.CharField(max_length=2, null=True, verbose_name="Вольер")
    user_id = models.CharField(max_length=10, null=True, verbose_name="Хозяин")
    photo = models.ImageField(upload_to='animals/%Y/%m/%d', blank=True)

    def __str__(self):
        return self.animal_card

shelter/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from .models import Animal, Color, Weight


# from .forms import AnimalRegistrationForm


def index(request):
    animal_list = Animal.objects.all()
    context = {
        'animal_list': animal_list
    }
    return render(request, 'shelter/main.html', context)


def search_page(request):
    animal_list = Animal.objects.all()
    # img = request.animal.photo
    color_list = Color.objects.all()
    weight_list = Weight.objects.all()
    context = {
        'animal_list': animal_list,
        'color_list': color_list,
        'weight_list': weight_list
    }
    return render(request, 'shelter/pets.html', context)


def send_query(request):
    animal_list = Animal.objects.all()
    color_list = Color.objects.all()
    if request.POST['color'] != 'None':
        for color in color_list:
            if color.color_value == request.POST['color']:
                color_id = color.id
                break
        animal_list = Animal.objects.filter(animal_color=color_id)
    if request.POST['ears'] != 'None':
        animal_list = Animal.objects.filter(animal_ears=request.POST['ears'])
    if request.POST['size'] != 'None':
        animal_list = Animal.objects.filter(animal_size=request.POST['size'])
    if request.POST['age'] != 'None':
        animal_list = Animal.objects.filter(animal_age=request.POST['age'])
    # if request.POST['weight'] != 'None':
    #     animal_list = Animal.objects.filter(animal_ears=request.POST['weight'])
    if request.POST['breed'] != 'None':
        animal_list = Animal.objects.filter(animal_breed=request.POST['breed'])
    if request.POST['wool'] != 'None':
        animal_list = Animal.objects.filter(animal_wool=request.POST['wool'])
    if request.POST['tail'] != 'None':
        animal_list = Animal.objects.filter(animal_tail=request.POST['tail'])
    return animal_list


def search_filter(request):
    weight_list = Weight.objects.all()
    color_list = Color.objects.all()
    if request.method == 'POST':
        animal_list = send_query(request)
        context = {
            'animal_list': animal_list,
            'weight_list': weight_list,
            'color_list': color_list
        }
        return render(request, 'shelter/pets.html', context)

shelter/templates/shelter/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="../../static/shelter/css/main.css">
    <link rel="stylesheet" type="text/css" href="../../static/shelter/css/pets.css">
    <link rel="stylesheet" type="text/css" href="../../static/shelter/css/slider.css">
	<script type="text/javascript" src="../../static/shelter/js/script.js"></script>
     <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="wrapper">
        <div class="announcement">
            <p> announcement Text</p>
            <div class="announcement__close"></div>
        </div>
        <div class="header-wrapper">
		<header>
			<div class="header__topSegment">
				<div class="header__left">
					<!-- <div class="header__left__logo"></div>
					<div class="header__left__buttons">
						<div class="header__left__buttons__ourPets"></div>
						<div class="header__left__buttons__contacts"></div>
					</div>
			 -->
				</div>
				<div class="header__center">
					<div class="header__center__logo"></div>
				</div>
				<div class="header__right">
					<div class="header__right__buttons">
						<div class="header__right__buttons__autorization"><a href="{% url 'account:account' %}">ff</a></div>
						<div class="header__right__buttons__databaseEditing"></div>
					</div>

				</div>
			</div>
			<div class="header__bottomSegment">-->
                <ul class="header__bottomSegment__nav">
                    <a href="{% url 'shelter:index' %}"><li class="header__bottomSegment__nav__item">Главная</li></a>
                    <a href="{% url 'shelter:search_page' %}"><li class="header__bottomSegment__nav__item">Выбрать питомца</li></a>
                    <li class="header__bottomSegment__nav__item">Контакты</li>
                    <li class="header__bottomSegment__nav__item">О нас</li>
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'account:dashboard' %}">Hello {{ request.user.username }},
                    <a href="{% url 'account:logout' %}" ><li class="header__bottomSegment__nav__item">Выход</li></a>
                    {% else %}
                    <a href="{% url 'account:login' %}"><li class="header__bottomSegment__nav__item">Вход</li></a>
                    {% endif %}
                    </a>
                </ul>
            </div>
		</header>
	</div>
            {% block content %}
            {% endblock %}
        </div>

	<footer>
		<p>Все права защищены ©2020</p>
	</footer>
	<script type="text/javascript" src="../../static/shelter/js/slider.js"></script>
</body>
</html>

shelter/templates/shelter/main.html
{% extends './base.html' %}
{% block content %}

	<div class="overlay">
		<div class="slides">
		  	<div class="slide 1th">
		  		<div class="slide__text">Text</div>
		  	</div>
		  	<div class="slide 2th">
		  		<div class="slide__text">Text 2</div>
		  	</div>
		 	 <div class="slide 3th">
		  		<div class="slide__text"></div>
		  	</div>
		  	<div class="slide 4th">
		  		<div class="slide__text"></div>
		  	</div>
		  	<div class="slide 5th">
		  		<div class="slide__text"></div>
		  	</div>
		</div>
		<div class="nav">
		  	<div class="btn-group">
				<div class="btn active"></div>
				<div class="btn"></div>
				<div class="btn"></div>
				<div class="btn"></div>
				<div class="btn"></div>
		  	</div>
		</div>
	</div>

	<content>
		<div class="section__0">
			<h2>Title</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>

<!--		<div class="section__ourPets">-->
			<h2>Наши питомцы</h2>
			<div class="section__ourPets__petcards">
				<div class="section__ourPets__petcards__wrapper">
					{% if animal_list %}
						{% for animal in animal_list %}
						<div class="petcards__item">
							<div class="petcards__item__img"></div>
							<div class="petcards__item__description">
								{% if animal.animal_name == None  %}
									<h2>Прикол</h2>
								{% else %}
									<h2>{{ animal.animal_name }}</h2>
								{% endif %}
								<span>Цвет: {{ animal.animal_color }}<br></span>
								<span>Размер: {{ animal.animal_size }}<br></span>
								<span>Представитель: <a href="{% url 'account:page' %}">{{ animal.user_id }}</a></span>
							</div>
							<div class="petcards__item__likeButton"></div>
						</div>
						{% endfor %}
						{% endif %}
				</div>
			</div>
<!--		</div>-->
	</content>
{% endblock %}

shelter/templates/shelter/pets.html
{% extends './base.html' %}
{% block content %}
		<content>
			<div class="section__petSearch">
				<h2>Найти друга</h2>
				<div class="searchForm">
					<form name="search_form" action="{% url 'shelter:search_filter' %}" method="POST">{% csrf_token %}
						<div class="registry-petCard">

							<div class="registry-petCard__cols">

								<div class="registry-petCard__cols__col2">
									<div class="registry-petCard__cols__col2__item">
										<p>Тип животного </p>
										<div class="pet_type">
											<select name="type">
												<option value='None'>Не выбрано</option>
												<option value="Собака">Собака</option>
												<option value="Кошка">Кошка</option>
											</select>
										</div>
									</div>
									<div class="registry-petCard__cols__col2__item">
										<p>Пол </p>
										<div class="pet_gender">
											<select name="gender">
												<option value='None'>Не выбрано</option>
												<option value="Мужской">Мужской</option>
												<option value="Женский">Женский</option>
											</select>
										</div>
									</div>

									<div class="registry-petCard__cols__col2__item">
										<p>Окрас </p>
											<div class="pet_color">
												<select name="color">
													{% if color_value %}
														<option value="{{ color_value }}">{{ color_value }}</option>
													{% else %}
														<option value='None'>Не выбрано</option>
													{% endif %}
													{% if color_list %}
														{% for color in color_list %}
															{% if color.color_value == None %}
																<option value="{{ color.color_value }}">Не выбрано</option>
															{% else %}
																<option value="{{ color.color_value }}">{{ color.color_value }}</option>
															{% endif %}
													{% endfor %}
													{% endif %}
												</select>
											</div>
										</div>
										<div class="registry-petCard__cols__col2__item">
											<p>Уши </p>
											<div class="pet_ears">
												<select name="ears">
													<option value='None'>Не выбрано</option>
													<option value="Стоячие">Стоячие</option>
													<option value="Полустоячие">Полустоячие</option>
													<option value="Висячие">Висячие</option>
													<option value="Купированные">Купированные</option>
												</select>
											</div>
										</div>
										<div class="registry-petCard__cols__col2__item">
											<p>Размер </p>
											<div class="pet_size">
												<select name="size">
													<option value='None'>Не выбрано</option>
													<option value="Средний">Средний</option>
													<option value="Малый">Малый</option>
													<option value="Крупный">Крупный</option>
												</select>
											</div>
										</div>
									</div>

									<div class="registry-petCard__cols__col3">
										<div class="registry-petCard__cols__col3__item">
											<p>Возраст, год </p>
											<div class="pet_age">
												<select name="age">
													<option value='None'>Не выбрано</option>
													<option value="<1"><1</option>
													<option value="1-5">1-5</option>
													<option value="5-10">5-10</option>
													<option value="10<">10<</option>
												</select>
											</div>
										</div>

										<div class="registry-petCard__cols__col3__item">
											<p>Вес,кг </p>
											<div class="pet_weight">
												<select name="weight">
<!--													{% if weight_value %}-->
<!--														<option value="{{ weight_value }}">{{ weight_value }}</option>-->
<!--													{% endif %}-->
													{% if weight_list %}
														{% for weight in weight_list %}
															<option value="{{ weight.weight_value }}">{{ weight.weight_value }}</option>
														{% endfor %}
													{% endif %}
												</select>
											</div>
										</div>

										<div class="registry-petCard__cols__col3__item">
											<p>Порода </p>
											<div class="pet_breed">
												<select name="breed">
													<option value='None'>Не выбрано</option>
													<option value="Метис">Метис</option>
												</select>
											</div>
										</div>

										<div class="registry-petCard__cols__col3__item">
											<p>Шерсть </p>
											<div class="pet_wool">
												<select name="wool">
													<option value='None'>Не выбрано</option>
													<option value="Короткая">Короткая</option>
													<option value="Обычная">Обычная</option>
													<option value="Длинная">Длинная</option>
												</select>
											</div>
										</div>

										<div class="registry-petCard__cols__col3__item">
											<p>Хвост</p>
											<div class="pet_tail">
												<select name="tail">
													<option value='None'>Не выбрано</option>
													<option value="Обычный">Обычный</option>
													<option value="Купированный">Купированный</option>
													<option value="Саблевидный">Саблевидный</option>
													<option value="Поленом">Поленом</option>
													<option value="Крючком">Крючком</option>
												</select>
											</div>
										</div>
									</div>
								</div>
							<div class="searchForm__buttons">
								<button type="submit" class="searchForm__buttons__button" value="Найти">Найти</button>
							</div>
						</div>
					</form>
				</div>

				<div class="searchResult">
					<div class="section__ourPets__petcards">
						<div class="section__ourPets__petcards__wrapper">
							{% if animal_list %}
							{% for animal in animal_list %}
							<div class="petcards__item">
								<div class="petcards__item__img"></div>
								<div class="petcards__item__description">
									{% if animal.animal_name == None  %}
										<h2>Прикол</h2>
									{% else %}
										<h2>{{ animal.animal_name }}</h2>
									{% endif %}
									<span>Цвет: {{ animal.animal_color }}</span>
									<span>Размер: {{ animal.animal_size }}</span>
									<span>Представитель: <a href="{% url 'account:page' %}">{{ animal.user_id }}</a></span>
								</div>
								<div class="petcards__item__likeButton" style="color: #fff"></div>
							</div>
							{% endfor %}
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</content>
{% endblock %}